### ISSUE TITLE
Improve legibility of icon labels over buildings

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#58]
Could be small building outline color changes.

**Comment by nvkelso** [comment]
Also having difficulty reading over large buildings. Wondering if we went too grey on the building strokes, too?

https://tangrams.github.io/tron/#18/40.70653/-74.00785

<img width="895" alt="screen shot 2016-09-06 at 21 27 14" src="https://cloud.githubusercontent.com/assets/853051/18299820/d61119a2-7478-11e6-8d6f-7fa1fae94a65.png">

**Comment by sensescape** [comment]
i tried to darken buildings here for label legibility:
before:
<img width="800" alt="screen shot 2016-09-07 at 2 53 22 pm" src="https://cloud.githubusercontent.com/assets/466585/18330029/4bc680d2-750b-11e6-85a5-8a10aca3bb5c.png">
after:
<img width="900" alt="screen shot 2016-09-07 at 2 53 29 pm" src="https://cloud.githubusercontent.com/assets/466585/18330042/58017b90-750b-11e6-9f59-391ada4cd373.png">

the change for that is here, line 120
https://github.com/tangrams/tron/commit/1726d4ef7cd6a5638c8204d7064bfa194781c16a

@patriciogonzalezvivo trying to darken the buildings colors a bit so that labels can read on top

but i really love what you've done with the buildings, and i'm hesitant to change it

what do you think we should do here? maybe colors get richer and more saturated vs. more white? but the glow and brightness looks so good, a bit torn, not sure what to do here.

**Comment by sensescape** [comment]
more tweaks here, what do you think? @patriciogonzalezvivo 

https://github.com/tangrams/tron/commit/0433f4b4741a346c9f4495a21a45404ce6073c96

before:
<img width="1044" alt="screen shot 2016-09-07 at 3 48 12 pm" src="https://cloud.githubusercontent.com/assets/466585/18331323/d453077a-7512-11e6-9a91-d87b5a046a9d.png">

after:
<img width="1079" alt="screen shot 2016-09-07 at 3 48 23 pm" src="https://cloud.githubusercontent.com/assets/466585/18331326/e027b834-7512-11e6-8e5a-69d9ee41631a.png">

**Comment by patriciogonzalezvivo** [comment]
well is important to read the labels : )
