### ISSUE TITLE
Adjust wave animation

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#87]
It probably shouldn't animate at low and mid zooms at all.

**Comment by sensescape** [comment]
we probably need a new layer at low zooms that doesn't use a shader

**Comment by patriciogonzalezvivo** [comment]
Are we talking about the coast lines waves? or the shimmering?I If is the first one, I think we don't need the the coast lines at all until very late... I can add a logic to the existing wave to not animate before zoom level # ... so we don't make another layer/shader. (because if it's the coastlines what we are talking about, they have a glow)

**Comment by sensescape** [comment]
yes the coastline waves, since we don't really see it animating until its a very thick line width at z18. yes, that sounds good!

**Comment by patriciogonzalezvivo** [comment]
@sensescape thinking more carefully... adding a flag on the shader will only reduce the efficiency. Because adds logic bifurcations to the shader with out preventing for rendering every frame. This should be address adding a different layer : / sorry

**Comment by sensescape** [comment]
ok! will do work on that this morning

**Comment by sensescape** [comment]
this is done:
https://github.com/tangrams/tron/commit/cd44b44b9d56d60dc3302d7b2822e751c21cdfd0

<img width="909" alt="screen shot 2016-09-12 at 11 02 48 am" src="https://cloud.githubusercontent.com/assets/466585/18446768/a1c115d0-78d8-11e6-8f19-df07ee999127.png">
